openapi: 3.0.0
info:
  title: 年月週管理マスタ
  description: 年月週管理マスタ情報のスキーマ情報
  version: 1.0.0
components:
 schemas:
  mNentsukiShuKanri:
   type: object
   description: 年月週管理マスタ情報（全列）
   required:
   - nentsuki
   - shu
   properties:
    nentsuki:
      type: integer
      maximum : 210012
      minimum : 199001
      description: 年月
    shu:
      type: integer
      maximum : 5
      minimum : 1
      description: 週
    shuFrom:
      type: string
      format: yyyy/MM/dd
      description: 週の開始日（日曜日）
    shuTo:
      type: string
      format: yyyy/MM/dd
      description: 週の終了日（土曜日）
    torokuDay:
      type: string
      format: yyyy/MM/dd
      description: 登録日
    koushinDay:
      type: string
      format: yyyy/MM/dd
      description: 更新日