openapi: 3.0.0
info:
  title: オンエア管理テーブル
  description: オンエア管理テーブル情報のスキーマ情報
  version: 1.0.0
components:
 schemas:
  tOnAirKanri:
   type: object
   description: オンエア管理テーブル情報（全列）
   required:
   - programId
   properties:
    id:
      type: string
      maxLength: 8
      description: ID
    onAirDay:
      type: string
      format: yyyy/MM/dd
      description: オンエア日
    programId:
      type: string
      maxLength: 8
      description: 番組ID
    talentId:
      type: string
      maxLength: 8
      description: タレントID
    nentsuki:
      type: integer
      maximum : 210012
      minimum : 199001
      description: 対象年月
    shu:
      type: integer
      maximum : 5
      minimum : 1
      description: 対象週
    deleteFlg:
      type: integer
      maximum : 9
      minimum : 0
      description: 論理削除フラグ
    torokuDay:
      type: string
      format: yyyy/MM/dd
      description: 登録日
    koushinDay:
      type: string
      format: yyyy/MM/dd
      description: 更新日